---
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - packages
    - luksbootkeyfile
    - plymouthcfg
    - initramfscfg
    - removeuser
    - initramfs
    - shellprocess:
        command: "/usr/local/bin/scarlix-wizard"
        timeout: 300
    - umount

showWelcome: true
confirmQuit: true
