services:
  piper-sk:
    image: rhasspy/wyoming-piper:1.5.0
    container_name: piper-sk
    restart: unless-stopped
    ports:
      - "127.0.0.1:8003:10200"
    volumes:
      - ./models:/voices:ro
    command: --voice sk_SK-lili-medium
    networks: [scarlix-net]
networks:
  scarlix-net: { external: true }
