package main

import (
        _ "embed"  // v18.5.1: blank import for //go:embed directive (Go 1.23 requires it)
        "log"
        "net/http"
        "os"
        "time" // v18.6 P1: explicit server timeouts

        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/api"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/guard"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/mcp"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/profiles"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/scarlix_mode"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/webui"
)

// Version is the ScarliHQ application version.
// v18.2 P1: Changed from `const` to `var` — ldflags `-X main.Version` only works on vars.
// v18.0.0: injected via -ldflags "-X main.Version=$VERSION" in Dockerfile.
// Default here matches VERSION file (used when running `go run` without ldflags).
var Version = "18.7.5"

//go:embed frontend/dist/index.html
var indexHTML []byte

func main() {
        log.SetFlags(log.LstdFlags | log.Lshortfile)
        log.Printf("SCARLIX OS %s — ScarliHQ starting (host-bridge architecture)...", Version)

        // Auth token: required for all /api/* and /ws. Generated by generate-env.sh
        // into /etc/scarlix/.env (SCARLIHQ_TOKEN). Passed to container via compose env.
        authToken := os.Getenv("SCARLIHQ_TOKEN")
        if authToken == "" {
                log.Println("WARNING: SCARLIHQ_TOKEN not set — dashboard API will reject all requests. Set SCARLIHQ_TOKEN in /etc/scarlix/.env")
        }

        // Initialize subsystems (all file-based — no privileged host access needed)
        g := guard.New()
        mode := scarlix_mode.New()
        pf := profiles.New("/etc/scarlix/profiles")

        mux := http.NewServeMux()

        // Dashboard HTML (served WITHOUT auth — it's a shell that needs a token to act).
        // v18.7.5 P0: JS reads token from sessionStorage only (was: also from ?token= URL).
        // Without it, shows a token-entry form (paste-once-per-session via auth gate).
        mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                if r.URL.Path != "/" {
                        http.NotFound(w, r)
                        return
                }
                w.Header().Set("Content-Type", "text/html; charset=utf-8")
                w.Header().Set("Cache-Control", "no-cache")
                w.Write(indexHTML)
        })

        // REST API + MCP + WS — all behind token auth
        // v18.2 P1: pass Version to Handler (was: separate const — ldflags couldn't override)
        apiHandler := api.NewHandler(g, mode, pf, authToken, Version)
        apiHandler.RegisterRoutes(mux)

        mcpServer := mcp.NewServer(g, mode, pf, authToken, Version)
        mcpServer.RegisterRoutes(mux)

        webui.RegisterWS(mux, authToken, mode, pf)

        // Start server
        port := os.Getenv("SCARLIHQ_PORT")
        if port == "" {
                port = "8090"
        }

        log.Printf("ScarliHQ %s listening on :%s", Version, port)
        // v18.7.5 P0: Removed ?token=<SCARLIHQ_TOKEN> from dashboard URL hint
        // (was: permanent token in URL → leaked in browser history/referrer/proxy logs).
        // Users now log in via the auth gate (token pasted once per browser session,
        // stored in sessionStorage — never in URL).
        log.Printf("Dashboard: http://localhost:%s/ (login with token from /etc/scarlix/.env)", port)
        log.Printf("REST API:    http://localhost:%s/api/*  (Bearer token)", port)
        log.Printf("MCP (JSON-RPC): http://localhost:%s/mcp  (Bearer token)", port)
        log.Printf("WebSocket:   ws://localhost:%s/ws?ticket=<one-time>  (POST /api/ws-ticket to obtain)", port)

        // v18.6 P1: Explicit HTTP server timeouts (was: ListenAndServe with no timeouts → slow-client DoS)
        srv := &http.Server{
                Addr:              ":" + port,
                Handler:           mux,
                ReadHeaderTimeout: 5 * time.Second,
                ReadTimeout:       15 * time.Second,
                WriteTimeout:      30 * time.Second,
                IdleTimeout:       60 * time.Second,
                MaxHeaderBytes:    1 << 20, // 1MB
        }
        if err := srv.ListenAndServe(); err != nil {
                log.Fatalf("Server failed: %v", err)
        }
}
