package main

import (
        "embed"
        "log"
        "net/http"
        "os"

        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/api"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/guard"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/mcp"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/profiles"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/scarlix_mode"
        "github.com/MoZoHuJa/scarlix-os-v12/scarlihq/internal/webui"
)

// Version is the ScarliHQ application version.
// v17.9.9 P2: injected via -ldflags "-X main.Version=$VERSION" in Dockerfile.
// Default here matches VERSION file (used when running `go run` without ldflags).
const Version = "17.9.9"

//go:embed frontend/dist/index.html
var indexHTML []byte

func main() {
        log.SetFlags(log.LstdFlags | log.Lshortfile)
        log.Printf("SCARLIX OS %s — ScarliHQ starting (host-bridge architecture)...", Version)

        // Auth token: required for all /api/* and /ws. Generated by generate-env.sh
        // into /etc/scarlix/.env (SCARLIHQ_TOKEN). Passed to container via compose env.
        authToken := os.Getenv("SCARLIHQ_TOKEN")
        if authToken == "" {
                log.Println("WARNING: SCARLIHQ_TOKEN not set — dashboard API will reject all requests. Set SCARLIHQ_TOKEN in /etc/scarlix/.env")
        }

        // Initialize subsystems (all file-based — no privileged host access needed)
        g := guard.New()
        mode := scarlix_mode.New()
        pf := profiles.New("/etc/scarlix/profiles")

        mux := http.NewServeMux()

        // Dashboard HTML (served WITHOUT auth — it's a shell that needs a token to act).
        // JS reads ?token= from URL; without it, shows a token-entry form.
        mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                if r.URL.Path != "/" {
                        http.NotFound(w, r)
                        return
                }
                w.Header().Set("Content-Type", "text/html; charset=utf-8")
                w.Header().Set("Cache-Control", "no-cache")
                w.Write(indexHTML)
        })

        // REST API + MCP + WS — all behind token auth
        apiHandler := api.NewHandler(g, mode, pf, authToken)
        apiHandler.RegisterRoutes(mux)

        mcpServer := mcp.NewServer(g, mode, pf, authToken, Version)
        mcpServer.RegisterRoutes(mux)

        webui.RegisterWS(mux, authToken, mode, pf)

        // Start server
        port := os.Getenv("SCARLIHQ_PORT")
        if port == "" {
                port = "8090"
        }

        log.Printf("ScarliHQ %s listening on :%s", Version, port)
        log.Printf("Dashboard:   http://localhost:%s/?token=<SCARLIHQ_TOKEN>", port)
        log.Printf("REST API:    http://localhost:%s/api/*  (Bearer token)", port)
        log.Printf("MCP (JSON-RPC): http://localhost:%s/mcp  (Bearer token)", port)
        log.Printf("WebSocket:   ws://localhost:%s/ws?token=<SCARLIHQ_TOKEN>", port)

        if err := http.ListenAndServe(":"+port, mux); err != nil {
                log.Fatalf("Server failed: %v", err)
        }
}
