efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB
efiSystemPartitionType: "default"
swapPartitionName: "swap"
drawNestedPartitions: true
alwaysShowPartitionLabels: true

defaultFileSystemType: "btrfs"

availableFileSystems:
  - btrfs
  - ext4
  - xfs

btrfsSubvolumes:
  - mountPoint: "/"
    subvolume: "@"
    name: "Root"

btrfsSwapSubvol: "@swap"

partitionLayout:
  - name: "EFI"
    filesystem: "fat32"
    mountPoint: "/boot/efi"
    size: 512MiB
    type: "ef00"
  - name: "Root"
    filesystem: "btrfs"
    mountPoint: "/"
    size: 100%
