userShell: /bin/bash
defaultGroups:
  - name: users
  - name: wheel
  - name: docker
  - name: video
  - name: audio
  - name: lp
  - name: network
  - name: storage
  - name: scanner
  - name: input
  - name: bluetooth

doAutologin: false
doReusePassword: false
passwordRequirements:
  minLength: 8
  maxLength: 200
  libpwquality:
    settings:
      minlen: 8
      minclass: 2

allowWeakPasswords: false
allowRootPassword: true
doNewUser: true
setRootPassword: true

# Pre-configured user
doAutoLogin: false
